#!/bin/python3

import json
import os.path
import re
import sys

pattern = re.compile(r'(\d|[A-Z]){10,}')

user_home = os.path.expandvars('$HOME') + '/'
Premium_path = user_home + '.config/navicat/Premium/'

preferences_json_path = Premium_path + 'preferences.json'
if os.path.exists(preferences_json_path):
    preferences_json_file = open(preferences_json_path)
    preferences_json: dict = json.load(preferences_json_file)

    for key in list(preferences_json.keys()):
        if pattern.match(key):
            preferences_json.pop(key)
    print('修改' + preferences_json_path + '文件')
    preferences_json_file.close()
    preferences_json_file = open(preferences_json_path, mode='w')
    json.dump(preferences_json, preferences_json_file)
    preferences_json_file.close()

usage_db_path = Premium_path + 'usage.db'
if os.path.exists(usage_db_path):
    print('删除' + usage_db_path + '文件')
    os.remove(usage_db_path)

argv = sys.argv
if len(argv) > 1:
    os.system(argv[1])
